services:
  - type: web
    name: my-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install -g pnpm
      pnpm install  # Hoặc dùng: npm install --legacy-peer-deps
    startCommand: |
      cd frontend
      npm run dev
    envVars:
      - key: PORT
        value: 3000  

  - type: web
    name: my-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
