services:
  - type: web
    name: my-frontend
    runtime: node
    plan: free
    buildCommand: |
      cd frontend
      NODE_OPTIONS="--max-old-space-size=1024" npm install --legacy-peer-deps
      NODE_OPTIONS="--max-old-space-size=1024" npm run build
    startCommand: |
      cd frontend
      PORT=$PORT npm run start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: my-backend
    runtime: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
